feat: add sample address buttons as input option
lukso-network/tools-erc725-inspect pull request #63
Opened 2023-11-14 13:59 UTC by fhildeb

2023-11-14 17:50 UTC, Esanim approved these changes

2023-11-14 17:50 UTC, Esanim commented on components/SampleAddressInput/SampleAddressInput.tsx
> +  onChangeFunction: (e: React.ChangeEvent<HTMLInputElement>) => void;
you can keep it as is (name), but you might as well shorten to just onChange

2023-11-15 09:09 UTC, Hugoo commented on components/SampleAddressInput/SampleAddressInput.tsx
> +        address = '0x6395b330F063F96579aA8F7b59f2584fb9b6c3a5';
Could you define these addresses in a const or global files - or at the very list at the top of this file.

It is important to give names to addresses as over time we don't know what is what.

```js
const SAMPLE_MAINNET_UP_ADDRESS = '';
const SAMPLE TESTNET_UP_ADDRESS = '0x9139def55c73c12bcda9c44f12326686e3948634';

// NOTE: what kind of asset btw?
const SAMPLE_MAINNET_ASSET = '';
const SAMPLE_TESTNET_ASSET = '0x6395b330F063F96579aA8F7b59f2584fb9b6c3a5';
```

Also, you are using the same addresses for testnet and mainnet - is it intended? Let's not hide little "bombs" in the code, just change the address to empty string for MAINNET. At least it is clear that it is missing.

Having a testnet address like it is right not is wrong and might lead to problems.

2023-11-15 09:10 UTC, Hugoo commented on components/SampleAddressInput/SampleAddressInput.tsx
> +    let address;
```suggestion
    let address: string;
```

2023-11-15 09:14 UTC, Hugoo requested changes

2023-11-15 09:14 UTC, Hugoo commented on components/SampleAddressInput/SampleAddressInput.tsx
> +        address = '0x6395b330F063F96579aA8F7b59f2584fb9b6c3a5';
Consider using a switch case

2023-11-15 09:14 UTC, Hugoo commented on components/SampleAddressInput/SampleAddressInput.tsx
> +      const inputElement = document.getElementById(inputId) as HTMLInputElement;
we are working with react here - there should be no need to use plain js like that:

`document.getElementById(inputId) as HTMLInputElement;`

Consider using react with: refs:

https://react.dev/learn/manipulating-the-dom-with-refs

2023-11-15 09:14 UTC, Hugoo commented on components/SampleAddressInput/SampleAddressInput.tsx
> +    }
no need for that - this looks weird

2023-11-15 09:14 UTC, Hugoo commented on components/SampleAddressInput/SampleAddressInput.tsx
> +    }
Where is the element with `{inputId}` class defined??

Let's try to not hijack the system by targetting dom elements like that. I'm sure there is another easiest way.

2023-11-15 13:17 UTC, fhildeb commented
I've applied the suggestions, however one element had to stay:

```js
    if (address && inputRef.current) {
      inputRef.current.value = address;
      onChange({
        target: { value: address },
      } as React.ChangeEvent<HTMLInputElement>);
    }
```

As we are having one component that is used on 2 pages with different `onChange` behavior/functions for `<input>` elements, we have to pass the function into the component, so it can be called.

`onChange` is only triggered from manual user inputs, not if done by code. Thats why the function must be triggered manually after.

2023-11-16 10:06 UTC, Hugoo commented
@fhildeb i don't understand your comment. Please check my last commit: https://github.com/lukso-network/tools-erc725-inspect/pull/63/commits/b7b4b4f90d033ff3490ac3704e6db240ff7ed34e

2023-11-16 10:06 UTC, Hugoo approved these changes

2023-11-16 10:07 UTC, merged